### PR TITLE
Social links

### LINKED ISSUE #13: Add link to cloudnativejs twitter and slack on homepage
Would be good to help advertise our channels. Could just be a twitter logo / 'follow us on twitter' + slack logo somewhere in or near the footer. Potentially a new section like 'get in touch' / 'lets chat'. Footer could be nice if it would persist to other pages

Could also add somewhere on the about (slack link is already there) and contact pages

Twitter: https://twitter.com/cloudnativejs
Slack Direct Link: https://node-js.slack.com/messages/CBV29RX62/ , Registration: http://www.nodeslackers.com/ , Channel: cloudnative

### PR DESCRIPTION
**Pull request by neeraj-laad**
Have added twitter and github links to the footer.

Decided to not include Slack icon just yet as that needs to be accompanied with registration information that can't possible fit in the footer.

resolves #13

### CODE REVIEW

**Comment by neeraj-laad** [comment]
Current:

screen shot 2018-09-04 at 11 56 33

**Comment by neeraj-laad** [comment]
Updated:

screen shot 2018-09-04 at 11 56 00

**Comment by sympatheticmoose** [comment]
Have you tested on safari, firefox, chrome, desktop/mobile? 

Given section has both twitter and github, may be better to omit the 'follow us' text since that doesnt make sense for the latter. Also, from the commits I can't see how you're including the twitter and github logos?

**Comment by neeraj-laad** [comment]
- Apologies I should have made that clear. Yes, I did test on desktop / mobile and also on Chrome, Firefox, Safari. Have not tested it on IE/Edge though.

- OK removed the 'Follow us:' text so now we just have two icons on the right.

- The icons are part of the IBM Northstar library that we are using for the footer. I've added the colour myself in the css though as that makes them more prominent. Hope that is OK.

**Comment by gdams** [comment]
Offical Link: https://nodejs.org/static/documents/trademark-policy.pdf

```Node.js is a trademark of Joyent, Inc. and is used with its permission. We are not endorsed by or 
affiliated with Joyent.” ```

**Comment by seabaylea** [comment]
Is this ready to go?

**Comment by gdams** [comment]
yes

**Comment by seabaylea** [comment]
LGTM. Merging.

**Pull request merged**
