### PR TITLE
Add Express Gateway to the project

### PR DESCRIPTION
**Pull request by XVincentX**
Hey — you probably remember me, we met at Node Summit and I've been speaking with Chris about featuring Express Gateway as the API Gateway for the project.

This is just a start — I'd love to iterate more with you on this.

Cheers!

### CODE REVIEW

**Comment by XVincentX** [comment]
//cc @seabaylea @BethGriggs

**Comment by XVincentX** [comment]
Latest master merged.

**Comment by seabaylea** [comment]
Hi @XVincentX. Sorry - I completely missed that you'd raised this PR.

It looks like you've raised a PR to provide an official Helm chart, which is fantastic! Does the deployed gateway support liveness, open tracing and prometheus etc? Are you doing anything to provide annotation based registration of APIs into the gateway?

**Comment by XVincentX** [comment]
We have an official Helm chart now.

**Comment by gdams** [comment]
ping @seabaylea

**Comment by XVincentX** [comment]
It seems like the website has been changing since my PR @gdams 

I want to make sure the maintainers are going to accept the PR before rebasing.

**Comment by XVincentX** [comment]
@gdams Any update on this?

**Pull request closed without merging**
